#!/bin/bash
# up-casa.sh [--run DIR] [--deploy DIR] - build the simulated family home:
#   RUN/     casa world state: lan shims + hosts dir, dns mode files, scripted
#            disk table, generated certs, control plane (casa-ctl + PATH stubs)
#   DEPLOY/  a deployment root copied from authoring/scripts (the soak layer's
#            install; the cloud drill layer installs with scripts/install.sh
#            instead - see sim/CLOUD-TEST.md) + the casa overlay (rendered
#            services.json, casa-sink.sh, casa-restart.sh)
# Writes RUN/env.sh with everything children need. Defaults:
#   RUN    sim/.run/casa     DEPLOY $RUN/deploy
# Note: the ping shim is sandbox/lan/ping unmodified; it reads $SANDBOX_RUN,
# so env.sh exports SANDBOX_RUN=$CASA_RUN (documented in sim/README.md).
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"          # sim/casa
SIM="$(cd "$HERE/.." && pwd)"                  # sim
REPO="$(cd "$SIM/.." && pwd)"                  # repo root
RUN="$SIM/.run/casa"
DEPLOY=""
while [ $# -gt 0 ]; do
    case "$1" in
        --run)    RUN="$2"; shift 2 ;;
        --deploy) DEPLOY="$2"; shift 2 ;;
        *) echo "usage: up-casa.sh [--run DIR] [--deploy DIR]" >&2; exit 64 ;;
    esac
done
[ -n "$DEPLOY" ] || DEPLOY="$RUN/deploy"

# tear down any previous world (kill stale fake-service listeners first)
if [ -d "$RUN/lan/pids" ]; then
    for p in "$RUN"/lan/pids/*.pid; do
        [ -e "$p" ] && kill "$(cat "$p")" 2>/dev/null || true
    done
fi
rm -rf "$RUN"
mkdir -p "$RUN/lan/hosts" "$RUN/lan/pids" "$RUN/dns" "$RUN/vol/tank" \
         "$RUN/vol/root" "$RUN/certs" "$RUN/bin"

echo "== casa world ($RUN)"
cp "$REPO/sandbox/lan/ping" "$REPO/sandbox/lan/fake-service.py" "$RUN/lan/"
cp "$HERE/casa.json" "$RUN/"
cp "$HERE/casa-ctl" "$HERE/make-cert.sh" "$HERE/bin/dig" "$HERE/bin/df" "$RUN/bin/"
chmod +x "$RUN/bin/"* "$RUN/lan/ping"

export CASA_RUN="$RUN" SANDBOX_RUN="$RUN"
for ip in 192.168.1.2 1.1.1.1 8.8.8.8; do echo up > "$RUN/dns/$ip"; done
printf '{"%s": 40, "%s": 55}\n' "$RUN/vol/tank" "$RUN/vol/root" > "$RUN/disk-table.json"
echo ok > "$RUN/tg-mode"
bash "$RUN/bin/make-cert.sh" truenas 90
for ip in 192.168.1.1 192.168.1.2 192.168.1.3 192.168.1.4; do
    "$RUN/bin/casa-ctl" plug "$ip"
done

echo "== deploy ($DEPLOY)"
rm -rf "$DEPLOY"
mkdir -p "$DEPLOY"
cp -R "$REPO/authoring/scripts/." "$DEPLOY/"
cp "$HERE/overlay/bin/casa-sink.sh" "$DEPLOY/bin/"
cp "$HERE/overlay/remediations/casa-restart.sh" "$DEPLOY/remediations/"
chmod +x "$DEPLOY/bin/casa-sink.sh" "$DEPLOY/remediations/casa-restart.sh"
sed -e "s#@RUN@#$RUN#g" -e "s#@CASACTL@#$RUN/bin/casa-ctl#g" \
    "$HERE/overlay/services.casa.json" > "$DEPLOY/services.json"
mkdir -p "$DEPLOY/state"

cat > "$RUN/env.sh" <<ENV
# generated by up-casa.sh - everything a child of the sim needs
export CASA_RUN="$RUN"
export SANDBOX_RUN="$RUN"        # the reused sandbox ping shim reads this
export DEPLOY="$DEPLOY"
export PATH="$RUN/bin:$RUN/lan:\$PATH"
export SELFHEAL_GW_OVERRIDE="192.168.1.1"
export SELFHEAL_ALERT_FILE="$DEPLOY/state/alert-pending.json"
export TG_BOT_TOKEN="000000:FAKE-TOKEN"
export TG_CHAT_ID="1001"           # admin (Dana)
export TG_ANNOUNCE_CHAT_ID="2001"  # household (Sam + Riley)
# TG_API is set by the harness once the stub Bot API's port is known:
#   python3 sim/phone/stub_botapi.py --port P --log L --mode-file \$CASA_RUN/tg-mode
ENV

echo "Casa up. Next:  . $RUN/env.sh  then e.g.  python3 \$DEPLOY/engine/selfheal.py --once"
